### ISSUE TITLE
/biomeinfo not working

### ISSUE THREAD

**Issue by Ivan1874** [EngineHub/WorldEdit#1265]
/biomeinfo command not working in worldedit for fabric version 7.1.0

Stacktrace:
`java.lang.NoSuchMethodError: net.minecraft.class_1959.method_8693()Lnet/minecraft/class_2561;
        at com.sk89q.worldedit.fabric.FabricBiomeRegistry$FabricBiomeData.getName(FabricBiomeRegistry.java:54) ~[worldedit-fabric-mc1.15.2-7.1.0.jar:?]
        at com.sk89q.worldedit.command.BiomeCommands.lambda$biomeInfo$2(BiomeCommands.java:164) ~[worldedit-fabric-mc1.15.2-7.1.0.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_242]
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556) ~[?:1.8.0_242]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_242]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_242]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_242]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_242]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_242]
        at com.sk89q.worldedit.command.BiomeCommands.biomeInfo(BiomeCommands.java:168) ~[worldedit-fabric-mc1.15.2-7.1.0.jar:?]
        at com.sk89q.worldedit.command.BiomeCommandsRegistration.cmd$biomeinfo(BiomeCommandsRegistration.java:156) ~[worldedit-fabric-mc1.15.2-7.1.0.jar:?]
        at org.enginehub.piston.CommandManager.execute(CommandManager.java:158) ~[worldedit-fabric-mc1.15.2-7.1.0.jar:?]
        at com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommand(PlatformCommandManager.java:486) ~[worldedit-fabric-mc1.15.2-7.1.0.jar:?]
        at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
        at com.sk89q.worldedit.util.eventbus.MethodEventHandler.dispatch(MethodEventHandler.java:58) ~[worldedit-fabric-mc1.15.2-7.1.0.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[worldedit-fabric-mc1.15.2-7.1.0.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[worldedit-fabric-mc1.15.2-7.1.0.jar:?]
        at com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[worldedit-fabric-mc1.15.2-7.1.0.jar:?]
        at com.sk89q.worldedit.fabric.CommandWrapper.lambda$register$0(CommandWrapper.java:65) ~[worldedit-fabric-mc1.15.2-7.1.0.jar:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[intermediary-server.jar:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176) ~[intermediary-server.jar:?]
        at net.minecraft.class_2170.method_9249(class_2170.java:235) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_14370(class_3244.java:1083) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12048(class_3244.java:1070) ~[intermediary-server.jar:?]
        at net.minecraft.class_2797.method_12115(class_2797.java:36) ~[intermediary-server.jar:?]
        at net.minecraft.class_2797.method_11054(class_2797.java:9) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) [intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:144) [intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:743) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:138) [intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:118) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:725) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:719) [intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:127) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:704) [intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:659) [intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]`

**To Reproduce**
Select a region and issue /biomeinfo command

**Expected behavior**
Command shows current biome info

**Additional context**
Fabric version: 0.7.8+build.189
Minecraft version: 1.15.2

**Comment by me4502** [comment]
Did you have any other mods? This shouldn't be possible with the way Fabric works

**Comment by Ivan1874** [comment]
no, only fabric-api-0.5.1+build.294-1.15, modmenu-1.10.2+build.32 and worldedit-fabric-mc1.15.2-7.1.0
