### ISSUE TITLE
WorldEdit (Fabric *Server* 1.15.2) Crashes: NoClassDefFoundError

### ISSUE THREAD

**Issue by LadyCailinBot** [EngineHub/WorldEdit#1256]
WORLDEDIT-4038 - Reported by CODY_AI

The latest version for available for Fabric crashes on the serve
But it does work on a 1.15.1 server

Main cause: Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_2960
